version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5673:5672
        - 15673:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_nodejs
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      timeout: 15s
      retries: 1
    logging:
      driver: none


  server:
    build: ./server
    volumes:
      - ./server/src:/home/node/app/src
    environment:
      NODE_ENV: production
      AMQP_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy
    links: 
        - rabbitmq
    networks:
      - rabbitmq_nodejs
    ports:
      - 8081:3000
      - 8080:8080
    
networks:
  rabbitmq_nodejs:
    driver: bridge

